# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66a8c1218b69e841b2408c554e51599994fd1cb4ab5ef2e2a08840dec44da0ba6d15e989d7017dbf4df6b0b635dec9623c5f33ddc61895b9dadef4b2767c1cfe

test:
  secret_key_base: b566d3d703329779b710468758c51509e860a65fc6e426913d49eb6c3c6e66c77380c38660a305f4281d7e7cc59d6cfc7f7a6d620791678df20f35570f3e5126

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
